### PR TITLE
STORY 2678 modify fetch_csv: removes aoData from params to fetchCSV, …

### PR DESCRIPTION
**Pull request by trevorfrese**
…adds error handling for goToWindowLocation

@InvokeJLa can I get a CR?

### CODE REVIEW

**Comment by InvokeJLa** [comment]
Wait this is just a updating the auto generated distribution file, right? Because the previous PR had this in the source files?

**Comment by trevorfrese** [comment]
Crap. You're right I didn't realize that it was in the last PR. Sorry about that. Yes this would only update the dist. Is it worth it to keep dist up to date?

**Comment by InvokeJLa** [comment]
Yeah, we need to keep the dist file updated since that's what goes out to apps that use backdraft.

**Comment by InvokeJLa** [comment]
:+1:

**Pull request merged**
